name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.nhrnick.us.kg", custom_domain = true },
  { pattern = "quey.nhrnick.us.kg", custom_domain = true },
  { pattern = "gcr.nhrnick.us.kg", custom_domain = true },
  { pattern = "k8s-gcr.nhrnick.us.kg", custom_domain = true },
  { pattern = "k8s.nhrnick.us.kg", custom_domain = true },
  { pattern = "ghcr.nhrnick.us.kg", custom_domain = true },
  { pattern = "cloudsmith.nhrnick.us.kg", custom_domain = true },
  { pattern = "go.nhrnick.us.kg", custom_domain = true },
  { pattern = "te.nhrnick.us.kg", custom_domain = true },
  { pattern = "dockerhub.nhrnick.us.kg", custom_domain = true },
  { pattern = "planel4server00.nhrnick.us.kg", custom_domain = true },
  { pattern = "github.nhrnick.us.kg", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.nhrnick.us.kg", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""

